function report = run_behavior_discrepancy_exploration()
% RUN_BEHAVIOR_DISCREPANCY_EXPLORATION
% Run the add-on diagnostics without changing the r00-r06 reproduction
% pipeline or existing results files.

script_dir = fileparts(mfilename('fullpath'));
addpath(script_dir);
cfg = r00_setup();
out_dir = fullfile(cfg.out_results, 'exploration');
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

fprintf('[explore] Writing diagnostic outputs only under: %s\n', out_dir);
nan_diag = explore_nan_unusable_distribution(cfg, out_dir);
source_diag = explore_fig2_source_subject_diffs(cfg, out_dir, nan_diag);

report = struct();
report.nan_diag = nan_diag;
report.source_diag = source_diag;
report.summary_md = fullfile(out_dir, 'behavior_discrepancy_exploration_summary.md');

write_summary(report.summary_md, cfg, nan_diag, source_diag);
save(fullfile(out_dir, 'behavior_discrepancy_exploration_all.mat'), ...
    'nan_diag', 'source_diag', 'report');

fprintf('[explore] Summary written to %s\n', report.summary_md);
end

function write_summary(path_out, cfg, nan_diag, source_diag)
fid = fopen(path_out, 'w', 'n', 'UTF-8');
if fid < 0
    error('Could not write summary: %s', path_out);
end
clean = onCleanup(@() fclose(fid));

class_counts = nan_diag.global_class_counts;
session_counts = nan_diag.global_session_counts;
group_sens = nan_diag.group_sensitivity;
contrast_sens = nan_diag.contrast_sensitivity;
subj_summary = sortrows(nan_diag.subject_summary, 'n_unusable', 'descend');
top_error = source_diag.top_error;
top_rt = source_diag.top_rt;
pair_summary = source_diag.pair_summary;

total_trials = sum(class_counts.n_trials);
total_unusable = sum(class_counts.n_unusable);

fprintf(fid, '# Behavior Discrepancy Exploration Summary\n\n');
fprintf(fid, 'Generated by `code/explore/run_behavior_discrepancy_exploration.m`.\n\n');
fprintf(fid, '## Scope\n\n');
fprintf(fid, '- Read-only inputs: current `normalized_eye_data/`, `gaze_shift/`, `event_TAN_mini1/`, `behavior_aligned/`, and `results/GA_behavior_stats.mat`.\n');
fprintf(fid, '- New outputs only: `results/exploration/`.\n');
fprintf(fid, '- No `code/reproduce/r00-r06` scripts or existing `results/*.mat` / `results/figures/*.png` files are written by these diagnostics.\n\n');

fprintf(fid, '## Script Outputs\n\n');
fprintf(fid, '- `nan_unusable_distribution.mat` plus CSVs for subject summaries, trial flags, breakdowns, and current-vs-exclude-unusable sensitivity.\n');
fprintf(fid, '- `fig2_source_subject_diffs.mat` plus CSVs for local-vs-Source-Data subject-condition differences and trial-level inspection of top deviations.\n');
fprintf(fid, '- `behavior_discrepancy_exploration_all.mat` stores both diagnostic structs.\n\n');

fprintf(fid, '## NaN / Unusable Distribution\n\n');
fprintf(fid, '- Total unusable trials: %d / %d = %.2f%%.\n', ...
    total_unusable, total_trials, 100 * total_unusable / total_trials);
fprintf(fid, '- By trial class:\n\n');
fprintf(fid, '| class | n trials | n unusable | unusable %% | valid RT n | mean error | mean RT |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|\n');
for i = 1:height(class_counts)
    fprintf(fid, '| %s | %d | %d | %.2f | %d | %.3f | %.2f |\n', ...
        class_counts.class_name{i}, class_counts.n_trials(i), ...
        class_counts.n_unusable(i), 100 * class_counts.unusable_rate(i), ...
        class_counts.n_valid_RT(i), class_counts.mean_error_validRT(i), ...
        class_counts.mean_RT_validRT(i));
end
fprintf(fid, '\n- By session:\n\n');
fprintf(fid, '| session | n trials | n unusable | unusable %% | valid RT n |\n');
fprintf(fid, '|---:|---:|---:|---:|---:|\n');
for i = 1:height(session_counts)
    fprintf(fid, '| %d | %d | %d | %.2f | %d |\n', ...
        session_counts.session(i), session_counts.n_trials(i), ...
        session_counts.n_unusable(i), 100 * session_counts.unusable_rate(i), ...
        session_counts.n_valid_RT(i));
end

fprintf(fid, '\n- Top subjects by unusable count:\n\n');
fprintf(fid, '| subject | unusable / total | unusable %% | noMS unusable | toward unusable | away unusable | trimmed RT |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|\n');
for i = 1:min(8, height(subj_summary))
    fprintf(fid, '| %s | %d / %d | %.2f | %d | %d | %d | %d |\n', ...
        subj_summary.subject{i}, subj_summary.n_unusable(i), subj_summary.n_total(i), ...
        100 * subj_summary.unusable_rate(i), subj_summary.n_unusable_noMS(i), ...
        subj_summary.n_unusable_toward(i), subj_summary.n_unusable_away(i), ...
        subj_summary.n_trimmed_RT(i));
end

fprintf(fid, '\n## Excluding Unusable: Behavior Sensitivity\n\n');
fprintf(fid, '| condition | current n | exclude-unusable n | removed validRT n | current error | excl error | delta error | current RT | excl RT | delta RT |\n');
fprintf(fid, '|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n');
for i = 1:height(group_sens)
    fprintf(fid, '| %s | %.1f | %.1f | %.1f | %.3f | %.3f | %.3f | %.2f | %.2f | %.2f |\n', ...
        group_sens.condition{i}, group_sens.mean_n_current(i), ...
        group_sens.mean_n_exclude_unusable(i), group_sens.mean_n_removed_unusable_validRT(i), ...
        group_sens.mean_error_current(i), group_sens.mean_error_exclude_unusable(i), ...
        group_sens.delta_error_exclude_minus_current(i), group_sens.mean_RT_current(i), ...
        group_sens.mean_RT_exclude_unusable(i), group_sens.delta_RT_exclude_minus_current(i));
end

fprintf(fid, '\nPaired contrasts:\n\n');
fprintf(fid, '| measure | policy | contrast | mean diff | t | p raw | p Bonf3 | n |\n');
fprintf(fid, '|---|---|---|---:|---:|---:|---:|---:|\n');
for i = 1:height(contrast_sens)
    fprintf(fid, '| %s | %s | %s | %.3f | %.3f | %.4f | %.4f | %d |\n', ...
        contrast_sens.measure{i}, contrast_sens.policy{i}, contrast_sens.contrast{i}, ...
        contrast_sens.mean_diff(i), contrast_sens.t_value(i), ...
        contrast_sens.p_raw(i), contrast_sens.p_bonf3(i), contrast_sens.n(i));
end

fprintf(fid, '\n## Fig. 2 Source Data Comparison\n\n');
fprintf(fid, '- Source Data sanity check: %d rows, subjectID header row %d, cache `%s`.\n', ...
    source_diag.source_meta.row_count, source_diag.source_meta.header_row, ...
    source_diag.source_meta.cache_file);
fprintf(fid, '- Mean absolute error diff by condition: %.3f / %.3f / %.3f deg.\n', ...
    source_diag.mean_abs_diff_error(1), source_diag.mean_abs_diff_error(2), source_diag.mean_abs_diff_error(3));
fprintf(fid, '- Mean absolute RT diff by condition: %.2f / %.2f / %.2f ms.\n\n', ...
    source_diag.mean_abs_diff_RT(1), source_diag.mean_abs_diff_RT(2), source_diag.mean_abs_diff_RT(3));

fprintf(fid, 'Top error differences:\n\n');
fprintf(fid, '| subject | condition | local error | paper error | abs diff | valid n | unusable class n | trimmed class n |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|---:|---:|\n');
for i = 1:min(8, height(top_error))
    fprintf(fid, '| %s | %s | %.3f | %.3f | %.3f | %d | %d | %d |\n', ...
        top_error.subject{i}, top_error.condition{i}, top_error.local_error(i), ...
        top_error.paper_error(i), top_error.abs_diff_error(i), top_error.local_n_valid(i), ...
        top_error.local_n_unusable_class(i), top_error.local_n_trimmed_class(i));
end

fprintf(fid, '\nTop RT differences:\n\n');
fprintf(fid, '| subject | condition | local RT | paper RT | abs diff | valid n | unusable class n | trimmed class n |\n');
fprintf(fid, '|---|---|---:|---:|---:|---:|---:|---:|\n');
for i = 1:min(8, height(top_rt))
    fprintf(fid, '| %s | %s | %.2f | %.2f | %.2f | %d | %d | %d |\n', ...
        top_rt.subject{i}, top_rt.condition{i}, top_rt.local_RT(i), ...
        top_rt.paper_RT(i), top_rt.abs_diff_RT(i), top_rt.local_n_valid(i), ...
        top_rt.local_n_unusable_class(i), top_rt.local_n_trimmed_class(i));
end

fprintf(fid, '\nTrial-level inspection of selected top deviations:\n\n');
fprintf(fid, '| subject | condition | source rank | abs error diff | abs RT diff | valid n | valid unusable n | small-before-kept n | near time boundary n | near size boundary n |\n');
fprintf(fid, '|---|---|---|---:|---:|---:|---:|---:|---:|---:|\n');
for i = 1:height(pair_summary)
    fprintf(fid, '| %s | %s | %s | %.3f | %.2f | %d | %d | %d | %d | %d |\n', ...
        pair_summary.subject{i}, pair_summary.condition{i}, pair_summary.source_rank{i}, ...
        pair_summary.abs_diff_error(i), pair_summary.abs_diff_RT(i), ...
        pair_summary.n_valid_RT(i), pair_summary.n_validRT_unusable(i), ...
        pair_summary.n_small_before_kept(i), pair_summary.n_close_time_boundary_10ms(i), ...
        pair_summary.n_close_size_boundary_0p9_1p1pct(i));
end

fprintf(fid, '\n## Ranked Interpretation\n\n');
fprintf(fid, '1. Most supported: NaN/unusable policy mismatch. The paper Methods say 0-600 ms NaN trials were dismissed before classification, while current outputs retain them in the main labels. The impact is condition-asymmetric, especially in noMS.\n');
fprintf(fid, '2. Subject-specific RT trimming is a separate contributor, especially for top RT deviations such as high-trim subjects in the Source Data comparison.\n');
fprintf(fid, '3. `<1%%` and first-shift boundary trials remain plausible local contributors. The top-pair trial detail CSV flags small-before-kept and near-boundary cases for direct inspection.\n');
fprintf(fid, '4. Source Data row alignment is less likely than the above because the workbook parser passed the header/row sanity checks, but the Source Data still cannot prove it came from the identical intermediate trial table.\n\n');

fprintf(fid, '## Still Uncertain\n\n');
fprintf(fid, '- The exact NaN cluster morphology produced by the authors original EDF-to-ASC/FieldTrip read path cannot be reconstructed from the current saved outputs alone.\n');
fprintf(fid, '- The public `sortTrial_onSaccade.m` code and the paper Methods differ in explicit unusable-trial handling, so the intended execution path is still ambiguous.\n');
fprintf(fid, '- The Source Data workbook provides subject-level condition means, not the original trial table, so trial inclusion cannot be matched one-for-one.\n');
fprintf(fid, '- Boundary definitions used here are diagnostic flags only: time boundary is within 10 ms of 200/600 ms, and size boundary is 0.9-1.1%% normalized shift size.\n');

fprintf(fid, '\n## Re-run Command\n\n');
fprintf(fid, '```matlab\ncd(''%s''); addpath(''code/reproduce''); addpath(''code/explore''); run_behavior_discrepancy_exploration\n```\n', cfg.repo_root);
end
